linz/nz-buildings

docs/source/conf.py

Fixes:
- Fixes reading of files in conf.py. I learned you can't remove items from a list while iterating over the list.
...

Fix reading sql files

---

.travis.yml

Small change to the travis configuration to test more PostgreSQL db versions.
Does not change anything locally, just adds more test environments to Travis-CI.

Add matrix to travis configuration to test more pg versions

---

sql/04-lookup_table_values.sql

Fixes:  https://github.com/linz/qgis-buildings-plugin/issues/32
New value added to bulk_load_status lookup table

New lookup table entry

---

docs/source/internal_data.rst
docs/source/introduction.rst
docs/source/published_data.rst

Fixes: #122 
Fixes: #123 
- Added some more URL links
- Replaced LDS with LINZ Data Service
- A little rewording
- I haven't tested the changes on RTD.

Doc review

---

sql/10-buildings_bulk_load_functions.sql

Fixes: #132 
Requires PR: https://github.com/linz/qgis-buildings-plugin/pull/40
Related to PR: https://github.com/linz/qgis-topoutilities-plugin/pull/42
function added to buildings_bulk_load allowing the bulk load status to be updated

Add change bulk load status of small buildings functionality

---

sql/04-lookup_table_values.sql
sql/10-buildings_bulk_load_functions.sql

Related to PR: https://github.com/linz/qgis-buildings-plugin/pull/109
Please see the other PR linked above

Allow removed outlines to be 'not removed'

---

tests/testdata/02-insert_test_data_buildings_bulk_load.sql
tests/testdata/06-insert_test_data_buildings_bulk_load_plugin.sql

to fit with changes in plugin
Fixes: https://github.com/linz/qgis-buildings-plugin/issues/85
small changes to test data to align with plugin changes

capture source updates

---

sql/09-buildings_functions.sql
sql/10-buildings_bulk_load_functions.sql

Fixes:  https://github.com/linz/qgis-buildings-plugin/pull/114
Please see the other PR above :)

Move update statements from plugin scripts

---

.travis.yml
docs/source/conf.py

Fixes: #167 
Changed the the function `setup_html_context` to get the name_key from the schema file's directory path and sorted the list alphabetically. 
This has not been tested

change conf.py for new database structure

---

sql/buildings_bulk_load/functions/07-added.sql
sql/buildings_bulk_load/functions/08-removed.sql
sql/buildings_bulk_load/functions/09-related.sql
sql/buildings_bulk_load/functions/10-matched.sql

Fixes: https://github.com/linz/qgis-buildings-plugin/issues/115
Updated/added functions to added, removed, related and matched to remove these from plugin code
Required for changes on PR: https://github.com/linz/qgis-buildings-plugin/pull/122

Plugin sql restructure

---

db/docs/source/DOCUMENTATION.rst

Fixes: #215 
Just added a few lines to mention how to build locally.
...

Added info for building local

---

metadata/nz_building_outlines_full_history.xml

Fixes: #211   
_Creating metadata for the NZ Buildings Full History set_
Metadata file created
...
Check consistency and wording makes sense. 
...

Full History Dataset Metadata

---

CHANGELOG.rst
README.rst
db/docs/source/introduction.rst
db/scripts/nz-buildings-load.in
db/sql/buildings_common/01-create-schema-and-tables.sql
db/sql/buildings_lds/01-create-schema-and-tables.sql
db/sql/buildings_lds/functions/02-nz_building_outlines_all_sources.sql
db/sql/buildings_lds/functions/05-populate_buildings_lds.sql
db/tests/buildings_lds_populate.pg
db/tests/testdata/10-create_test_aerial_schema.sql
install.py
makefile
metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml
metadata/nz_building_outlines_lifecycle.xml

Fixes: #257
Fixes: #112 
* Add additional capture source attributes to published datasets
* Simplify date fields
* Implement default values for published data
* Add constraints to published data
* Add new LDS links to metadata and data dictionary
* pgTAP tests adjusted

Adjust published datasets based on user feedback

---

.travis.yml
docker-compose.yml
install.py

Refer: #339 
Upgraded travis to run on QGIS3

Travis upgrade

---

CHANGELOG.rst

doc(changelog): update the date and version

---

CHANGELOG.rst

Fixes: #  update changelog from release
...

build: update changelog

---

metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml

Fixes: updated dates for metadata

docs: updated metadata

---

.gitlint
CHANGELOG.rst
db/sql/sqitch.plan

Update CHANGELOG and sqitch tag in preparation for release 3.2.0

release(3.2.0): update changelog and sqitch tag

---

.github/workflows/build.yml
CHANGELOG.rst

Github Actions to run on Pull Request

---

.github/workflows/build.yml
CHANGELOG.rst

Fixes: dependencies install failing in github action
fixed dependencies installation

ci: fix pgtap

---

db/docs/source/introduction.rst

Fixes: #421   
Dates updated for future coverage.
References to Image 5 and 6 corrected.
...
...

docs: update future coverage dates

---

metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml
metadata/nz_building_outlines_lifecycle.xml

Update metadata for Nelson 2019 building outlines release

---

metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml
metadata/nz_building_outlines_lifecycle.xml

Update metadata for Otago 2020 building outlines release

---

metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml
metadata/nz_building_outlines_lifecycle.xml

Update metadata for Dunedin 2018-2019 building outlines release

---

metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml

Metadata updates for hospitals and schools.
...
...

Hospitals and schools

---

metadata/nz_building_outlines.xml

Fixes: #  
LDS team let us know we needed to fix some URL links for Arc services.

fix: update arcgis links

---

.readthedocs.yaml

Fixes: #  TDP-271
Read the docs needs an updated .readthedocs.yaml file with minor changes

docs: update yaml

---

db/docs/source/conf.py

Fixes: #  
adding rtd extension in conf.py
...
...

docs: add sphinx rtd extension

---

db/docs/source/conf.py

Fixes: #  
removed extension, removed rtd theme
...
...

docs: remove rtd theme

---

db/docs/source/conf.py

Fixes: #  
convert to pyramid theme
...
...

docs: convert to pyramid theme

---

db/docs/source/conf.py

Fixes: #  
update to bizstyle theme
...
...

docs: update to bizstyle theme

---

db/docs/source/_static/custom.css

Fixes: #  
add a wider page
...
...

docs: wider page

---

db/docs/source/_static/custom.css

Fixes: #  
update page width
...
...

docs: update page width

---

db/docs/source/_static/custom.css

Fixes: #  
update body width css
...
...

docs: update body width

---

db/docs/source/_static/custom.css

Fixes: #  
add 1200x to nav content
...
...

docs: update 1200px

---

db/docs/source/introduction.rst

Fixes: #  
updated location of text, removed download tag
...
...

docs: updated location of text, removed download tag

---

db/docs/source/introduction.rst

Fixes: #  
removed forward slash in path
...
...

docs: removed forward slash

---

db/docs/source/introduction.rst

Fixes: #  
remove dots
...
...

docs: remove dots

---

db/docs/source/_static/default.css
db/docs/source/conf.py

Fixes: #  
new css over ride
...
...

docs: update how default css over ride

---

db/docs/source/conf.py

Fixes: #  
back to standard css
...
...

docs: back to standard css

---

db/docs/source/conf.py

Fixes: #  
undo over ride
...
...

docs: undo over ride

---

db/docs/source/conf.py

docs: no theme specified

---

db/docs/source/introduction.rst

Fixes: #  
remove scale
...
...

docs: remove scale

---

db/docs/source/conf.py
requirements-docs.txt

Fixes: #  
set sphinx theme
...
...

docs: set sphinx theme version

---

requirements-docs.txt

docs: version 7 sphinx

---

db/docs/source/introduction.rst

Fixes: #  
_Add new line for each issue that was fixed_
...
...

docs: remove scales

---

metadata/nz_building_outlines.xml
metadata/nz_building_outlines_all_sources.xml
metadata/nz_building_outlines_lifecycle.xml

Fixes: #  
update for the metadata description and dates for publishing

fix: update working on the description, & dates
