linz/nz-buildings

sql/12-alter_relationships_create_view.sql
Fixes: https://github.com/linz/qgis-buildings-plugin/issues/35
The views created for 'alter-building-relationships' will only display one dataset which is processed but not yet transferred to production.
run `sudo make install && make check` in this directory  and open the views in `nz-buildings-pgtap-db -> buildings_bulk_load`. The views will only show the supplied_dataset_id: 2 and 4
=> update 'create view' to display only one dataset

sql/09-buildings_functions.sql, tests/buildings_functions.pg
Fixes: # https://github.com/linz/qgis-buildings-plugin/issues/28
Required for PR: https://github.com/linz/qgis-buildings-plugin/pull/39
Two new functions added to buildings schema to update `building_outlines` attributes and geometries
=> Edit Functions added to buildings schema

sql/reference/01-buildings_reference_schema.sql
Fixes: #137
Spatial indexes added for `suburb_locality`, `town_city`, `territorial_authority` and `capture_source_area`.
`sudo make uninstall && make clean && sudo make install && make check`
=> Add missing spatial indexes for reference data

scripts/nz-buildings-load.in, sql/12-alter_relationships_create_view.sql, tests/buildings_bulk_load_create_view.pg
Fixes: #141 
Remove the function `buildings_bulk_load.create_building_relationship_view()`. The script will create views directly instead of create the function.
Steps to reproduce the behavior:
1. Run nz-buildings-load [database] to create a empty database
2. Open database and there should be views created in the buildings_bulk_load schema
=> Remove "create views" function

sql/08-admin_boundary_functions.sql, tests/admin_boundary_functions.pg
Related to https://github.com/linz/qgis-buildings-plugin/pull/82
remove `st_expand` in town/city intersecting function
=> remove `st_expand` in town/city intersecting function

scripts/nz-buildings-load.in, tests/extensions.pg
Fixes: #154 
Clarify that `intarray` should be installed in the `public` schema.
- New `extensions.pg` file added to test suite that checks existence of extensions.
=> Specify schema for installation of intarray extension

sql/buildings_bulk_load/functions/12-deletion_description.sql
Fixes: https://github.com/linz/qgis-buildings-plugin/issues/138
delete_deleted_description function added to all for the reversion of deleting building outlines
=> function to delete from deleted table

buildings/gui/alter_building_relationships.py, buildings/gui/production_changes.py, buildings/gui/production_edits.ui, buildings/gui/production_frame.py, buildings/sql/buildings_bulk_load_select_statements.py, buildings/sql/buildings_select_statements.py, buildings/tests/gui/test_processes_edit_attribute_production.py, db/sql/buildings/functions/02-use.sql, db/sql/buildings/functions/05-building_name.sql, db/sql/buildings/functions/06-building_use.sql, db/sql/buildings_bulk_load/functions/06-existing_subset_extracts.sql, db/sql/buildings_bulk_load/functions/08-removed.sql
Fixes: #186 
Button added to production frame allowing the user to end the lifespan of a building in production, when under then edit attribute option. 
The button will update the end lifespan field of the outline in the building_name, building_use, building_outlines and buildings tables as well as, if appropriate, remove the outline from the existing subset extracts and removed tables. The end lifespan button will give an error dialog if the outline is currently matched/related to an outline of the most recent bulk loaded dataset. The user can only end the lifespan of a building like this after the outlines have been 'unlinked'.
=> Allow User to End Lifespan of Building in Production

buildings/gui/bulk_load.py, buildings/gui/bulk_load_frame.py, buildings/gui/new_entry.py, buildings/sql/buildings_common_select_statements.py, buildings/tests/gui/test_processes_bulk_load_outlines.py
Fixes: #188 
During bulk loading new outlines, external source id combo box will change whenever capture source group combo box changed.
Test added in `test_processes_bulk_load_outlines`
=> Fix external_source_id combo box populating error

makefile
Fixes: #185 
when `make check_ui_headers` is run using the makefile all headers in the .ui files are updated/reverted to `<header>qgis.gui</header>`
To test change a header line in a .ui file, run `make check_ui_headers`, reload .ui file and code will change back to qgis.gui
=> .ui file headers fix

.travis.yml
Fixes: #207
- Travis configuration changed to use build stages
- Build stages are required to ensure that docs and database tests pass before automatically deploying the QGIS plugin on the plugin tests job
- Check new output in Travis
- Zip file deployment is functional
=> Use Travis build stages and deploy zip automatically

CHANGELOG.rst, makefile
Fixes: #209
Adds a utility to the makefile that updates the version number for the plugin, database and user.
`make bump_version TODAY=$(date '+%d-%m-%Y') VERSION=1.0.7` then check changes to files in git
=> Add utility to help with incrementing the version

CHANGELOG.rst
Simple change to remove the spaces to the left of bullet points in the CHANGELOG so that it renders correctly in GitHub.
=> Remove spaces to the left of bullet points in CHANGELOG

CHANGELOG.rst, buildings/gui/bulk_load.py, buildings/gui/bulk_load.ui, buildings/gui/bulk_load_changes.py, buildings/gui/bulk_load_frame.py, buildings/gui/new_capture_source.py, buildings/gui/production_changes.py, buildings/sql/buildings_common_select_statements.py, buildings/sql/buildings_reference_select_statements.py, buildings/tests/gui/test_processes_add_bulk_load.py, buildings/tests/gui/test_processes_add_production.py, buildings/tests/gui/test_processes_bulk_load_outlines.py, buildings/tests/gui/test_processes_comparison.py, buildings/tests/gui/test_processes_comparison_not_intersect.py, buildings/tests/gui/test_processes_edit_attribute_bulk_load.py, buildings/tests/gui/test_processes_edit_attribute_production.py, buildings/tests/gui/test_processes_publish.py, buildings/tests/gui/test_setup_bulk_load_outlines.py
Fixes: #247 
Display the name and id of capture source area in the cmb in `bulk load frame` and `production frame`.
In `production frame`, the capture source combo box will update according to the location of the adding outlines and only show the intersecting capture source area(s). This attribute can be edit in `edit attribute` if needed.
Change `cmb_external_id` to `cmb_capture_source_area` to avoid confusion against `fcb_external_id`
Update tests, run all tests.
=> Display capture source area title in combo box

CHANGELOG.rst, buildings/gui/comparisons.py, buildings/sql/buildings_select_statements.py
Fixes: #254 
Fix one select_statement in the sql folder to fix the bug
Install the test data and publish
Bulk load the shapefile testdata, compare and click "copy&match"/"Not removed" button on one of the removed outlines
Bulk load the shapefile again and hit compare. See if the "not removed" outline can be seen in the relationship frame
=> Bug fixed: "Not removed" outlines not being carried through while comparing

CHANGELOG.rst, db/docs/source/conf.py
Fixes: #264 
Added data type in function "**get_columns**" called 
`"integer_unique_not_null".`
It should handle a integer column whether or not it also contains "null_null" or not.
Screenshot of correct result:
...
=> UNIQUE update

CHANGELOG.rst, buildings/gui/bulk_load_changes.py, buildings/gui/production_changes.py
Fixes: #277 
Warning messages added to bulk load and production frame when multiple outlines are added
=> Warning messages on adding buildings

CHANGELOG.rst, buildings/gui/bulk_load_changes.py, buildings/gui/edit_dialog.py
Fixes: #293  
In bulk load frame, when geometry is changed or outline is deleted QA layers (if exist) will be updated so users don't have to switch between building plugins to LIQA
Bonus: Edit dialog will be re-focused every time users add a outline or edit a geometry so changes can be simply saved by click `ENTER`.
No test has been updated.
- Run LIQA to create a qa layer. 
- Choose one of the features that have been picked up and `Edit geometry`. 
- Save the changes and open error inspector to see the update.
- Repeat the process for 'Delete outline'.
=> Edit dialog updates QA layer

CHANGELOG.rst, buildings/gui/bulk_load_changes.py, buildings/gui/bulk_load_frame.py, buildings/gui/edit_dialog.py, buildings/gui/production_changes.py, buildings/tests/gui/test_processes_edit_geometry_bulk_load.py
Fixes: #290 
The user is now able to use the QGIS Split Features tool ![image](https://user-images.githubusercontent.com/33814653/58513568-d90c2a80-81f3-11e9-8d83-8b4ffcea5975.png) while in 'edit geometry' of the buildings plugin. 
Previously the bulk_load_changed.EditGeometry class did not account for any added geometries and there when used the geometry was still updated but the new split geometry was not added. This has now been fixed. 
new tests added
@jducnuigeen can you please check this functionality matches what you requested to split geometries at planning? :slightly_smiling_face:
=> Split features while editing- Bulk Load

CHANGELOG.rst, buildings/gui/bulk_load_changes.py, buildings/gui/edit_dialog.py, buildings/gui/production_changes.py, buildings/tests/gui/test_processes_add_bulk_load.py, buildings/tests/gui/test_processes_add_production.py
Fixes: #282   
When users add multiple outlines in one time, only the last one will be save. Previously when users tried to revert changes by ctrl+z or deleting, the last added outlines would be saved. The bug has been fixed by saving the id and geom of all added outlines in an `OrderedDict`. You can
- Click on `ctrl+z` to remove the last added outline. (need to click on the qgis main window as edit dialog will be on the top)
- Delete last added outline and save the previous outline.
- Edit the last added outline and save the new geometry.
- Edit any previous outline will be saved in the dictionary but will NOT be saved in the database if there's another outline added after it. You can remove the last one in order to save your changes.
Tests updated.
=> Fix the bug when reverting changes during add outlines

CHANGELOG.rst, buildings/gui/edit_dialog.py
Fixes: https://github.com/linz/qgis-liqa-plugin/issues/222
Link to another PR: https://github.com/linz/qgis-liqa-plugin/pull/223
In the code we use `_repopulate` from liqa plugin which could be easily broken if other devs change the name and at the moment we don't have a test for it. So I pulled out the function `repopulate_error_attribute_table` to LIQA
In LIQA, switch to branch `on_qa_layer_attribute_change` (has been merged into `master`) and 
- Run LIQA to create a qa layer.
- Choose one of the features that have been picked up and Edit geometry.
- Save the changes and open error inspector to see the update.
- Repeat the process for 'Delete outline'.
=> Pull out LIQA functionality from buildings plugin

db/sql/verify/buildings/schema_and_tables.sql, db/sql/verify/buildings_bulk_load/schema_and_tables.sql, db/sql/verify/buildings_common/schema_and_tables.sql, db/sql/verify/buildings_reference/schema_and_tables.sql
Fixes: #307 
Uses an `IS NULL` check rather than an `IS NOT FOUND` check to verify sequences.
- `sqitch verify`
=> Fix sequence verify statements so that they actually verify sequences

.travis.yml, CHANGELOG.rst
Fixes: #321 
Add `dist` setting in travis-ci config so the distribution for builds stays as `Trusty`.
See travis-ci result
=> Fix failing travis-ci

CHANGELOG.rst, buildings/reference_data/topo50.py, db/scripts/nz-buildings-load.in, db/sql/deploy/buildings_reference/functions/change_reference_name_col_insert.sql, db/sql/revert/buildings_reference/functions/change_reference_name_col_insert.sql, db/sql/sqitch.plan, db/sql/verify/buildings_reference/functions/change_reference_name_col_insert.sql, db/tests/buildings_reference.pg, install.py
Fixes: #323 
`Sqitch rework` on hut_points, shelter_points, bivouac_points and proctected_area_polygons so the name variable of those reference can be updated.
Plugin function `Correct_name_format` is used because name string like `Poor Pete's Hut`(it's a real hut) will raise database error when running sql query. 
Use the plugin to update reference. See if the name variable is added
=> Include the name variable inserts and updates for the reference

buildings/gui/edit_dialog.py
Fixes: #342 
missing hut qa layer doesn't have a "bulk_load_" field. Here I add a check so it will skip those layers
follow the steps on the issue to try to reproduce the error
=> bug fix - fail to find "bulk_load_" field in qa_missing_hut layer

.gitlint, .pre-commit-config.yaml, .travis.yml, CHANGELOG.rst, README.rst, requirements-dev.txt
Working towards https://github.com/linz/topo-tasks/issues/321
Adds `pre-commit` to create a `gitlint` configuration
README updated with installation instructions.
=> Add pre-commit to lint git commit messages to match conventional commits spec

CHANGELOG.rst, buildings/gui/alter_building_relationships.py, buildings/gui/bulk_load_changes.py, buildings/gui/bulk_load_frame.py
Fixes: #349   
Code added to:
- Fix the described vertex editing bug in alter relationships
- Allow the user to split buildings and then editing the new geometry without having to exit the frame (in both alter relationships and bulk load)
The functionality to split buildings was not incorporated into the production frame initially. To get this fix in before the next round of QA this has been added to another issue: https://github.com/linz/nz-buildings/issues/354
=> Vertex Editing Bug in Alter Relationships and Bulk Load

CHANGELOG.rst, buildings/gui/production_changes.py, buildings/gui/production_frame.py, buildings/sql/buildings_common_select_statements.py, buildings/styles/production_outlines.qml, buildings/tests/gui/test_processes_edit_geometry_bulk_load.py, buildings/tests/gui/test_processes_edit_geometry_production.py, buildings/tests/gui/test_processes_new_capture_source_area.py
Fixes: #354   
Editing geometry functionality has been updated to allow the user to split a feature in production. 
These changes were made in QGIS 3.10. It is important to note the plugin has not yet been completely migrated to QGIS 3.10. There are some portions of tests that have been commented out for the time being. A new issue will be made to address these. 
A test has been created for the new functionality though. 
To test:
- open the buildings plugin in QGIS
- open the production frame: 
- In the buildings toolbar select edit geometry and then split features
note: you can only spit one feature at a time, please follow the procedure: split > save >split/edit
=> Production split features

CHANGELOG.rst, buildings/gui/alter_building_relationships.py, buildings/metadata.txt, buildings/styles/building_editing.qml, buildings/styles/building_transparent.qml, buildings/styles/buildings_bulk_load_alter_rel.qml, buildings/tests/gui/test_processes_edit_geometry_bulk_load.py, buildings/tests/gui/test_processes_edit_geometry_production.py, docker-compose.yml
Fixes: #391  
Fixes: #367
- Failing tests fixed
- QgsHighlight issue resolved
- Previously the symbology of layers was 'simple fill' and when selected, the features had a filled selection obstructing the user from seeing the aerial imagery beneath. QgsHighlight was used to allow for a hollow selection.
- With upgrading the plugin to QGIS 3 a bug was observed with QgsHighlight, it was suggested this was an issue with QgsHighlight rather than the plugin.
- Changing the symbology of layers to 'Outline: simple line' in turn changed the selection visualisation to only select the outline of the feature. This change removes the need for a QgsHighlight in the buildings plugin and as such resolves the ongoing highlight bug. :tada:
Requires QGIS 3.10 for testing
To completely resolve the problem …
=> Complete upgrade 3.10

CHANGELOG.rst, buildings/gui/production_changes.py, buildings/gui/production_edits.ui, buildings/gui/production_frame.py, buildings/styles/historic_production_outlines.qml, buildings/tests/gui/test_processes_edit_geometry_production.py, db/sql/deploy/buildings/functions/insert_lifecycle_record.sql, db/sql/revert/buildings/functions/insert_lifecycle_record.sql, db/sql/sqitch.plan, db/sql/verify/buildings/functions/insert_lifecycle_record.sql, install.py
Fixes: #410  
Production logic altered to correctly edit a geometry:
- the existing geometry is retained and the lifespan is ended
- the two 'new' geometries are added with new ids
- the old ids and new ids are added to the lifespan table to retain the relationship
New test added
=> fix: fix splitting logic

CHANGELOG.rst, buildings/gui/bulk_load_changes.py, buildings/gui/edit_dialog.py, buildings/gui/edit_dialog.ui, buildings/tests/gui/test_processes_edit_attribute_bulk_load.py, buildings/tests/test_utilities.py
Fixes: #461
For the edit dialog instead of creating an error dialog we now have qgsmessagebar at the top of the dialog which populates with the error message.
The error message is warning level so it is highlighted, and has a time of 0 set so it doesn't disappear without the user removing it.
A layout has been added to the ui so this can be filled with the qgsmessagebar when initiating the edit dialog.
Only edit dialog adjust no other dialogs which also use the error dialog. If further ones cause problems these too can have a message bar added.
Modified test which failed as the closed the error dialog associated with the edit dialog, and this no longer exists. Instead of closing I clear all messages from the message bar. This is currently not really needed as we never check these …
=> Dialog warning

db/docs/source/introduction.rst, metadata/nz_building_outlines.xml, metadata/nz_building_outlines_all_sources.xml, metadata/nz_building_outlines_lifecycle.xml
Fixes: #  
This update publishes area 4, but since I've made a slight change to one of the image captions in the data dictionary, I'm using the branch from the last update, which never got merged to master.
In order for the Data Dictionary to update, this branch will need to be merged to master.
...
...
=> fix: update tank diameter, update metadata

buildings/plugin.py, buildings/tests/config.ini, buildings/tests/pg_config_test.ini, buildings/utilities/config.py, buildings/utilities/database.py, buildings/utilities/log.py, scripts/steps/setup_qgis_plugin.sh
This pull request implements the capability for logging, but does not itself implement any logging messages (to be implemented in further pull requests).
Logs are configured to be sent both to a logfile and to the QGIS GUI logs panel.
The logfile location is defined in the INI config file. Previously this INI file only stored database connection parameters, so the code which parses this has been expanded to account for the new information.
**This means the INI config file in use on any installations will need to be updated to include a logfile location.**
The following pattern can be used to add logging to a desired module:
```python
import logging
logger = logging.getLogger(__name__)
logger.info("Hello world")
```
Using `__name__` as the logger name will correctly scope the logger …
=> Add logging capability

buildings/gui/bulk_load.py, metadata/nz_building_outlines.xml, metadata/nz_building_outlines_all_sources.xml, metadata/nz_building_outlines_lifecycle.xml
Fixes: Issue TDP-207
Plugin had a bug where the capture source dialog during bulk load did not properly show the capture source - but instead left it in a blank state and produced no error during bulk load. Then, during comparisons, since the bulk load couldn't refer to the correct capture source, it referred to the first capture source in the list which was ID = 1000, and thus buildings outside of the bulk loaded extent were shown to be removed.
To solve this problem, we first identified those features outside of the capture extent which were incorrectly labelled for deletion. We then created a table of these and imported them as a temporary table into the buildings_reference schema.
We then deleted these buildings from these two tables using this SQL:
```
BEGIN;
DELETE FROM …
```
=> fix: update bulk load dialog, metadata

buildings/sql/buildings_select_statements.py
Currently when we start a comparison in alter relationships, the existing subset building outlines include buildings which cross the capture source boundary.
Since Lynker does not provide these buildings that cross the boundary, we have been noticing the alter relationships results show many buildings on the boundary as "removed", since those were not captured.
I struggle sometimes to follow what the plugin is doing, but from what I can tell the existing subset outline table is not populated until the comparisons step is run. I think.
If this is true, then when the comparisons.py script is run, in line 22:
```buildings_select.building_outlines_intersect_geometry, (hull,)```
the building outlines intersect geometry statement is run, and that is using an ST_Intersects, while it probably …
=> fix: adjust existing subset buildings

db/docs/source/conf.py
Fixes: #  
change theme to 'master' for readthedocs
...
...
=> docs: update as master theme

db/docs/source/_static/custom.css
Fixes: #  
div docwrapper and max width none
...
...
=> docs: div docwrapper and max width none

db/docs/source/_static/default.css, db/docs/source/conf.py
Fixes: #  
over ride css using default.css
...
...
=> docs: add default override

buildings/gui/bulk_load_frame.py
Fixes: #  
Bulk loading in QGIS 3.34 fails with error:
`2024-06-20T13:26:46     CRITICAL    Database Error : function buildings_bulk_load.supplied_outlines_insert(integer, numeric, unknown) does not exist
LINE 1: SELECT buildings_bulk_load.supplied_outlines_insert(81, 3357...
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.`
due to the bulk load frame having the external id field filled with a greyed out "fid"
This behavior did not exist in QGIS 3.10.
Forcing the field to be blank on loading the bulk load gui solves this problem.
This change also works with version 3.10.
Just adding one line to force the gui for external id to be blank on load event.
...
...
=> fix: blank external id field

buildings/gui/alter_building_relationships.py, buildings/sql/buildings_bulk_load_select_statements.py
Enables the sorting of alter relationships tables by name, to make it easier to make manual corrections to the data at the Alter Relationships stage.
Additional "name sort" drop-down options are added for Related, Matched, Removed, and Added tables.
Notes:
- enabling the built-in table sorting function with `tbl.setSortingEnabled(True)`, doesn't seem to work as it appears to lose persistent connection between the visual table in QGIS (after sorting) and the database table in Postgres.
- using a click listener with `tbl.horizontalHeader().sectionClicked.connect(self.idBulk)` and sorting with something like `result.sort(key=lambda i: i[4], reverse = True)`, also doesn't seem to work.
Bulk load some data, run Compare Outlines, then Alter Relationships.  Click on the drop-down menu and choose …
=> feat: add option to sort alter relationship tables by name

buildings/reference_data/topo50.py
Update the plugin so the coastline and island update process will project the data to 2193 
Run the updates for coastlines and islands in the plugin and check the geometry. (I've run the update today and the geometry is now in the right place)
=> feat: coastline and island - update coordinate system to 2193
